# UI Test Configuration

base.url=https://www.saucedemo.com
username=standard_user
password=secret_sauce

# Browser Configuration

browser=chrome
headless=false

implicit.wait=10
explicit.wait=15


# API Test Configuration

api.base.url=https://reqres.in
api.register.endpoint=/api/register
api.user.endpoint=/api/users/2
api.key=free_user_3EJHmCrNUqS0pH0c8SvBiXo9e0H
api.register.email=eve.holt@reqres.in
api.register.password=pistol